// WARNING: server-side skill — only enable for trusted contributors.
// Simple example that returns files to create (no direct shell exec).
module.exports.run = async function(input) {
  // input: { projectName, pages: [...] }
  const project = input.projectName || 'demo-site';
  const index = `<!doctype html><html><head><meta charset="utf-8"/><title>${project}</title></head><body><h1>${project}</h1><p>Generated by skill.</p></body></html>`;
  return { files: [{ path: `${project}/index.html`, content: index }] };
}
